/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuardraticVoting } from "./QuardraticVoting";

export { QuardraticVoting__factory } from "./factories/QuardraticVoting__factory";
